
# This is the user-interface definition of a Shiny web application.
# You can find out more about building applications with Shiny here:
# 
# http://www.rstudio.com/shiny/
#

library(shiny)

shinyUI(pageWithSidebar(
  # Application title
  headerPanel("Dirichlet Process Mixture Modelling"),
  
  # Sidebar with a slider input for number of observations
  sidebarPanel(
    tags$head( tags$script(src="http://cdn.mathjax.org/mathjax/2.0-latest/MathJax.js?config=TeX-AMS_HTML") ),
    
    p(strong("Generate Observations")),
    sliderInput("obs", 
                "Number of observations (\\( n \\)):", 
                min = 1, 
                max = 1000, 
                value = 500),
    sliderInput("K",
                "Number of clusters (\\( K \\))",
                 min = 1,
                max = 20,
                value = 4),
    sliderInput("alpha",
                "Concentration parameter (\\( \\alpha \\))",
                min = 0.1,
                max = 10,
                value = 1.1),
    numericInput("Rho",
                 "\\( \\rho \\): Variance of \\( \\theta_k \\)", value=1, min=0,max=100),
    matrixInput('Sigma', '\\( \\mathbf{\\Sigma} \\): Covariance Matrix of \\( x_i \\)', data.frame(diag(2))),
    wellPanel(
      p(strong("DP-Means")),
      sliderInput("lambda",
                  "Penalty parameter \\( \\lambda \\)",
                  min = 1,
                  max = 50,
                  value = 10,
                  animate = FALSE)
    )
      
  ),
  
  # Show a plot of the generated distribution
  mainPanel(
    tabsetPanel(
      tabPanel("DGP", plotOutput("distPlot"),
               HTML("Note: The data have been generated by drawing from the following process:
                      <ul>
                        <li> \\( \\mathbf{g} \\sim \\operatorname{Dir} (\\alpha, \\ldots, \\alpha) \\)</li>
                        <li> \\( \\forall k \\in \\{1, \\ldots, K\\} \\)
                              <ul> <li> \\( \\theta_k \\sim \\operatorname{MVNorm} \\left( 
                                    
                                    \\left(\\begin{array}{c}
                                    \\\\ 0
                                    \\\\ 0
                                    \\end{array}\\right),

                                    \\rho \\mathbf{I}

                                    \\right) \\) </li>
                              </ul>
                        </li>
                        <li> \\( \\forall i \\in \\{1, \\ldots, n\\} \\)
                              <ul>
                                <li> \\( z_i \\sim \\operatorname{Multinom} \\left( \\mathbf{g} \\right) \\)</li>
                                <li> \\( x_i \\sim \\operatorname{MVNorm} \\left(\\theta_{z_i}, \\mathbf{\\Sigma} \\right)\\)</li>
                              </ul>
                        </li>
                    </ul>")),
      tabPanel("Prediction",plotOutput("estPlot"),
               HTML("The DP-Means algorithm ('Revisiting k-means : New Algorithms via Bayesian Nonparametrics', Kulis et al),
                    converged in the following number of iterations:"),
               verbatimTextOutput("iterations")),
      tabPanel("Code",
               h3(HTML("Source Code")),
               HTML('<script src="https://gist.github.com/Planeshifter/4e512b6d842e1436768d.js"></script>')
               )
               )
          )
  )
)
